### ISSUE TITLE
Missing CanRDP edges

### ISSUE THREAD

**Issue by phosec** [BloodHoundAD/SharpHound#20]
Hey,

While working on a lab, I came across a strange issue,

A compromised user doesn't have the CanRDP edge using the latest collector,
I know people have seen this edge month ago, do you know what can be wrong ?

In execution right, everything is at 0 but the user is able to RDP.

Context of execution: user domain
Commandline: .\SharpHound.exe --CollectionMethods all,gpolocalgroup

If you have any idea how to troubleshoot this don't hesitate,

Thanks

**Comment by LyesH4ck** [comment]
Hi !

I have an issue  on MS02 (CLIENT.OFFSHORE.COM) when I run SharpHound.exe.
It's not possible to find way from owned users ... I got "NO DATA RETURNED FROM QUERY" for all my queries...
Links with AllowedToDelegate don't appears to .. It's really difficult to find a way with the last versions of SharpHound (1.03) / Bloodhound (4.1.0).

For your information I got better results with bloodhound.py even if it is not perfect...

I've tested SharpHound.ps1 and it's not possible to import the json file  in bloodhound anymore.

Regards,

**Comment by LyesH4ck** [comment]
For your information, I've just installed the old version (4.0.3) and tested it with SharpHound.Ps1 and All is OK  ! 
I can see all informations, all the way (canRDP, isAdmin, AllowToDelegate, ...)  ..so I think there is something wrong with the latest version of BloodHound  or SharpHound ..

**Comment by rvazarkar** [comment]
SharpHound.ps1 doesn't work for 4.1, the data formats are different. You can use the --DumpComputerStatus flag to see whats happening with computer connection API calls.

**Comment by LyesH4ck** [comment]
> SharpHound.ps1 doesn't work for 4.1, the data formats are different. You can use the --DumpComputerStatus flag to see whats happening with computer connection API calls.

I know that SharpHound.ps1 doesn't work with BH 4.1.
And I never used Sharphound.ps1 with BH 4.1. That's not at all what I said

The problem is with SharpHound 1.0.3 and BH 4.1... some Important links between machines to pwn the DC don't appears and Query from Owned User/machine doesn't work too.. 
This links appears when I use  bloodhound.py + BH 4.1 ... 

I've uploaded some screenshots in my last opened issue :
https://github.com/BloodHoundAD/SharpHound/issues/23

You can check them to compare. The results btw SharpHound 1.0.3 + BH 4.1 and SharpHound.ps1 + BH 4.0 are really different ...

I hope my issue  will be more clear for you.
If you are interested I can send you my dumps to test. 
Any way I will test .\SharpHound.exe --CollectAllProperties to test and I'll tell you. But I use the cmd  .\SharpHound.exe -c ALL and I think I will get the same result..

**Comment by LyesH4ck** [comment]
I've tested and I got the same result .. When I right click on DOC4 and select "Shortest Path To here" I don't see the link between MS02 and DC04 .. but that's the way to exploit it.
I can see this link when I use bloodhound.py... or if I use SharpHound.ps1 + BH 4.0.3...

**Comment by rvazarkar** [comment]
I'm a bit confused here since we didn't really change anything about the local group collection in 4.1. It would be helpful if you could run with the following flags:

```-v 0 -c LocalGroup --TrackComputerCalls```

The logfile + csv would help me figure out whats going on

**Comment by LyesH4ck** [comment]
> I'm a bit confused here since we didn't really change anything about the local group collection in 4.1. It would be helpful if you could run with the following flags:
> 
> `-v 0 -c LocalGroup --TrackComputerCalls`
> 
> The logfile + csv would help me figure out whats going on

Hello, 

[20220530053248_compstatus.csv](https://github.com/BloodHoundAD/SharpHound/files/8797282/20220530053248_compstatus.csv)
[20220530053248_BloodHound.zip](https://github.com/BloodHoundAD/SharpHound/files/8797283/20220530053248_BloodHound.zip)
[sharphound-output.log](https://github.com/BloodHoundAD/SharpHound/files/8797299/sharphound-output.log)

**Comment by rvazarkar** [comment]
So the computers were skipped because of their pwdlastset being > 60 days, which generally indicates a computer that doesn't exist. If this is in a lab, you can use the `--skippasswordcheck` flag I'm introducing in the next update
