### ISSUE TITLE
SharpHound v2.0.0 not compatible bloodhound v4.3.1

### ISSUE THREAD

**Issue by Bit-ByteBandit** [BloodHoundAD/SharpHound#61]
This is about Bloodhound version 5.0.0, which hasn't been released yet.

**Comment by StephenHinck** [comment]
I'm unclear what the specific issue is, so I'll cover a few things to try to clear up possible confusion:

- The name change to BloodHound CE coincides with code version 5.0.0 and is packaged with and works with SharpHound v2.0.
- SharpHound v2.0 is **incompatible** with BloodHound CE (v5.0) due to changes in the data schema for local group information.
- We are aware of and prepping a fix for the log line output by SharpHound v2.0 that indicates that it works with BloodHound v4.3.1.

**Comment by StephenHinck** [comment]
I'm going to close the issue, but please feel free to respond and re-open if you're still having an issue.
